# Muhammad Ali

Thời lượng ước tính: **120** phút

## Giới thiệu Lab
Trong quá trình trưởng thành, ai cũng hâm mộ một vị anh hùng. Đối với nhiều người, vị anh hùng đó là Muhammad Ali. Ông ấy dạy mọi người nên tự hào về con người của họ, kể cả vào thời điểm mà những người khác sẽ không chấp nhận điều đó. Ông đã chỉ cho mọi người cách đứng lên bảo vệ niềm tin khi đối mặt với áp bức và bạo quyền. Ông giúp mọi người đánh giá cao bản thân và khuyến khích họ quan tâm đến những người xung quanh. Ông đã cho chúng ta thấy bản lĩnh thực sự có nghĩa là gì, làm thế nào để trở thành một võ sĩ quyền anh, và nhiều hơn thế nữa. Tất cả những người từng gặp Muhammad Ali, dù là trên hay ngoài võ đài đều có một câu chuyện đầy động lực để chia sẻ về cuộc gặp gỡ của họ.

Vào ngày 3 tháng 6 năm 2016, Muhammad Ali qua đời ở tuổi 74 do sốc nhiễm trùng. Trước đó 30 năm, ông được chẩn đoán mắc hội chứng Parkinson, một tình trạng thoái hóa thần kinh mà các bác sĩ cho rằng do chấn thương não liên quan đến quyền anh.

Bản thân bệnh Parkinson là một rối loạn lâu dài của hệ thần kinh, ảnh hưởng đến nhiều khía cạnh vận động của một người theo thời gian. Người bệnh này có đặc điểm là run, di chuyển chậm, cứng nhắc, sa sút trí tuệ và trầm cảm. Vào năm 2013, khoảng 53 triệu người được chẩn đoán mắc bệnh này, chủ yếu là nam giới. Những nhân vật nổi tiếng khác bị ảnh hưởng bởi nó gồm diễn viên Michael J. Fox, và vận động viên đua xe đạp Olympic Davis Phinney.

Trong lab này, bạn sẽ áp dụng SVC cho [Tập dữ liệu Parkinson](https://archive.ics.uci.edu/ml/datasets/Parkinsons), được cung cấp bởi Machine Learning Repository của UCI. Tập dữ liệu được thực hiện ở Đại học Oxford, với sự hợp tác của 10 trung tâm y tế trên khắp Hoa Kỳ cùng với Intel, tổ chức đã phát triển thiết bị được sử dụng để ghi lại các thuộc tính chính của tập dữ liệu: tín hiệu giọng nói. Mục tiêu của bạn đối với lab này trước tiên là xem liệu có thể phân biệt được những người bị và không bị Parkinson sử dụng công cụ phân loại vectơ hỗ trợ của SciKit-Learn hay không, và sau đó là tìm hiểu một cách thuần phác trong việc tinh chỉnh các thông số với nỗ lực tối đa hóa độ chính xác của testing set.

"Tôi chưa bao giờ thực sự chán nản với những việc khó khăn bởi vì tôi luôn thích nó. Thức dậy mỗi sáng để làm việc trên đường. Đến phòng tập thể dục hàng ngày lúc 12 giờ. Tôi không bao giờ thay đổi khuôn khổ của mình."

## Chu kỳ 1

In [1]:
import pandas as pd
import numpy as np

Load **parkinsons.data** vào biến **X**, hãy chắc chắn rằng bạn bỏ cột name.


In [2]:
# Nhập code của bạn ở đây
X = pd.read_csv('parkinsons.data').drop(labels='name',axis = 1)
X

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0        119.992       157.302        74.997         0.00784   
1        122.400       148.650       113.819         0.00968   
2        116.682       131.111       111.555         0.01050   
3        116.676       137.871       111.366         0.00997   
4        116.014       141.781       110.655         0.01284   
..           ...           ...           ...             ...   
190      174.188       230.978        94.261         0.00459   
191      209.516       253.017        89.488         0.00564   
192      174.688       240.005        74.287         0.01360   
193      198.764       396.961        74.904         0.00740   
194      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0             0.00007   0.00370   0.00554     0.01109       0.04374   
1             0.00008   0.00465   0.00696     0.01394       0.06134   
2             0.00009   0.00544   0.00781     0.01633       0.05233   
3             0.00009   0.00502   0.00698     0.01505       0.05492   
4             0.00011   0.00655   0.00908     0.01966       0.06425   
..                ...       ...       ...         ...           ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087   
191           0.00003   0.00331   0.00292     0.00994       0.02751   
192           0.00008   0.00624   0.00564     0.01873       0.02308   
193           0.00004   0.00370   0.00390     0.01109       0.02296   
194           0.00003   0.00295   0.00317     0.00885       0.01884   

     MDVP:Shimmer(dB)  ...  Shimmer:DDA      NHR     HNR  status      RPDE  \
0               0.426  ...      0.06545  0.02211  21.033       1  0.414783   
1               0.626  ...      0.09403  0.01929  19.085       1  0.458359   
2               0.482  ...      0.08270  0.01309  20.651       1  0.429895   
3               0.517  ...      0.08771  0.01353  20.644       1  0.434969   
4               0.584  ...      0.10470  0.01767  19.649       1  0.417356   
..                ...  ...          ...      ...     ...     ...       ...   
190             0.405  ...      0.07008  0.02764  19.517       0  0.448439   
191             0.263  ...      0.04812  0.01810  19.147       0  0.431674   
192             0.256  ...      0.03804  0.10715  17.883       0  0.407567   
193             0.241  ...      0.03794  0.07223  19.020       0  0.451221   
194             0.190  ...      0.03078  0.04398  21.209       0  0.462803   

          DFA   spread1   spread2        D2       PPE  
0    0.815285 -4.813031  0.266482  2.301442  0.284654  
1    0.819521 -4.075192  0.335590  2.486855  0.368674  
2    0.825288 -4.443179  0.311173  2.342259  0.332634  
3    0.819235 -4.117501  0.334147  2.405554  0.368975  
4    0.823484 -3.747787  0.234513  2.332180  0.410335  
..        ...       ...       ...       ...       ...  
190  0.657899 -6.538586  0.121952  2.657476  0.133050  
191  0.683244 -6.195325  0.129303  2.784312  0.168895  
192  0.655683 -6.787197  0.158453  2.679772  0.131728  
193  0.643956 -6.744577  0.207454  2.138608  0.123306  
194  0.664357 -5.724056  0.190667  2.555477  0.148569  

[195 rows x 23 columns]

In [3]:
X.isnull().sum()

MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [4]:
X.dtypes

MDVP:Fo(Hz)         float64
MDVP:Fhi(Hz)        float64
MDVP:Flo(Hz)        float64
MDVP:Jitter(%)      float64
MDVP:Jitter(Abs)    float64
MDVP:RAP            float64
MDVP:PPQ            float64
Jitter:DDP          float64
MDVP:Shimmer        float64
MDVP:Shimmer(dB)    float64
Shimmer:APQ3        float64
Shimmer:APQ5        float64
MDVP:APQ            float64
Shimmer:DDA         float64
NHR                 float64
HNR                 float64
status                int64
RPDE                float64
DFA                 float64
spread1             float64
spread2             float64
D2                  float64
PPE                 float64
dtype: object

Ghép cột status vào biến **y** và xóa nó khỏi **X**.

In [5]:
# Nhập code của bạn ở đây
y = X['status'].values
X.drop(labels='status',axis = 1,inplace= True)

In [6]:
X.columns

Index(['MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)',
       'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP',
       'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'RPDE', 'DFA', 'spread1',
       'spread2', 'D2', 'PPE'],
      dtype='object')

Thực hiện train/test split. **30**% kích thước nhóm test, với random_state bằng **7**.

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=7)

In [9]:
print(X_train.shape)
print(y_train.shape)

(136, 22)
(136,)


Tạo bộ phân loại SVC. Không chỉ định bất kỳ tham số nào, chỉ để mọi thứ như mặc định. So khớp nó với dữ liệu huấn luyện và sau đó chấm điểm dữ liệu test với độ chính xác và F1 score.

In [10]:
# Nhập code của bạn ở đây
from sklearn import svm
clf = svm.SVC()
clf.fit(X_train, y_train) 

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [11]:
from sklearn.metrics import f1_score,accuracy_score

In [12]:
y_hat = clf.predict(X_test)
y_hat[0:5]

array([1, 0, 1, 1, 1], dtype=int64)

In [13]:
y_test[0:5]

array([0, 1, 1, 1, 1], dtype=int64)

In [14]:
print('Accuracy score: ',accuracy_score(y_test,y_hat))
print('F1 score:  ',f1_score(y_test,y_hat,average='weighted'))

Accuracy score:  0.7627118644067796
F1 score:   0.7302824858757062


## Chu kỳ 2


Độ chính xác đó quá thấp để trở nên hữu dụng. Chúng ta cần phải cải thiện nó. Bạn có thể thực hiện thử theo cách thủ công một loạt các kết hợp của **C và các giá trị gamma cho nhân rbf**. Nhưng điều đó có thể tốn rất nhiều thời gian. Ngoài ra, bạn có thể vô tình bỏ qua một cặp giá trị có thể dẫn đến độ chính xác rất tốt.

Thay vào đó, hãy tận dụng ưu điểm của máy tính. Lập trình tìm kiếm thông số tốt nhất đơn giản bằng cách tạo các vòng lặp for lồng nhau. Vòng lặp for bên ngoài sẽ lặp lại biến **C từ 0,05 đến 2, sử dụng tăng tiến đơn vị 0,05**. Vòng lặp for bên trong sẽ tăng biến **gamma từ 0,001 đến 0,1, sử dụng tăng tiến đơn vị 0,001**. Như bạn đã biết, Python range sẽ không cho phép khoảng thời gian thực, vì thế bạn sẽ phải thực hiện một số nghiên cứu về NumPy ARanges nếu bạn chưa biết cách sử dụng chúng.

Vì mục tiêu là tìm các tham số dẫn đến mô hình có hệ số chính xác tốt nhất, bạn sẽ cần biến **best_score = 0 mà bạn khởi tạo bên ngoài vòng lặp for.** Trong vòng lặp for bên trong, hãy tạo mô hình SVC và chuyển tham số C và gamma vào hàm tạo lớp. Huấn luyện và cho điểm mô hình một cách thích hợp. Nếu best_score hiện tại nhỏ hơn hệ số của mô hình, hãy cập nhật best_score để đảm bảo in nó ra cùng với các giá trị C và gamma dẫn đến nó.

Sau khi chạy lại lab, độ chính xác cao nhất và hệ số F1 mà bạn có thể nhận được là bao nhiêu?

In [21]:
# Nhập code của bạn ở đây
best_score = 0
for C in np.arange(0.05,2,0.05):
    for gamma in np.arange(0.001,0.1,0.001):
        model = svm.SVC(kernel='rbf',gamma=gamma,C=C)
        model.fit(X_train,y_train)
        score = model.score(X_test,y_test)
        if score > best_score:
            best_score = score
            best_C = C
            best_gamma = gamma 
        
print('High accuracy score: ',best_score)
print('Best C: ' ,best_C)
print('Best gamma: ',gamma)

High accuracy score:  0.9152542372881356
Best C:  1.6500000000000001
Best gamma:  0.099


## Chu kỳ 3

Đợi một chút. Kéo mở tệp nhãn của tập dữ liệu từ: https://archive.ics.uci.edu/ml/datasets/Parkinsons

Nhìn vào các đơn vị trên các cột: **Hz,%, Abs, dB, ...** Điều gì đã xảy ra với việc chuyển đổi dữ liệu? Tất cả các đơn vị đó tương tác với nhau, một số quá trình tiền xử lý chắc chắn là theo thứ tự.
Ngay sau khi bạn định dạng trước train/test split nhưng trước khi bạn huấn luyện mô hình, hãy nhập code tiền xử lý của SciKit-Learn. Trừ khi bạn biết rõ cái nào sẽ hoạt động tốt nhất, nếu không bạn sẽ phải thử từng bộ tiền xử lý khác nhau, kiểm tra xem chúng có cải thiện độ chính xác dự đoán hay không.

Hãy thử với ***Normalizer(), MaxAbsScaler(), MinMaxScaler(), KernelCenterer(), and StandardScaler().***

Sau khi thử tất cả các tỷ lệ này, độ chính xác cao nhất mới và hệ số F1 mà bạn có thể đạt được là bao nhiêu?

In [26]:
X = X.values

In [27]:
X[0:2]

array([[ 1.199920e+02,  1.573020e+02,  7.499700e+01,  7.840000e-03,
         7.000000e-05,  3.700000e-03,  5.540000e-03,  1.109000e-02,
         4.374000e-02,  4.260000e-01,  2.182000e-02,  3.130000e-02,
         2.971000e-02,  6.545000e-02,  2.211000e-02,  2.103300e+01,
         4.147830e-01,  8.152850e-01, -4.813031e+00,  2.664820e-01,
         2.301442e+00,  2.846540e-01],
       [ 1.224000e+02,  1.486500e+02,  1.138190e+02,  9.680000e-03,
         8.000000e-05,  4.650000e-03,  6.960000e-03,  1.394000e-02,
         6.134000e-02,  6.260000e-01,  3.134000e-02,  4.518000e-02,
         4.368000e-02,  9.403000e-02,  1.929000e-02,  1.908500e+01,
         4.583590e-01,  8.195210e-01, -4.075192e+00,  3.355900e-01,
         2.486855e+00,  3.686740e-01]])

In [28]:
from sklearn.preprocessing import Normalizer,MaxAbsScaler,MinMaxScaler,KernelCenterer,StandardScaler

In [29]:
normal = Normalizer().fit(X)
normal

Normalizer()

In [30]:
X_normal= normal.transform(X)

In [31]:
X_normal[0:2]

array([[ 5.64154193e-01,  7.39570829e-01,  3.52605774e-01,
         3.68605313e-05,  3.29111887e-07,  1.73959140e-05,
         2.60468551e-05,  5.21407261e-05,  2.05647913e-04,
         2.00288091e-03,  1.02588877e-04,  1.47160029e-04,
         1.39684488e-04,  3.07719614e-04,  1.03952340e-04,
         9.88887188e-02,  1.95014308e-03,  3.83314264e-03,
        -2.26289388e-02,  1.25289134e-03,  1.08204560e-02,
         1.33832879e-03],
       [ 5.45094429e-01,  6.61995808e-01,  5.06879925e-01,
         4.31087751e-05,  3.56270869e-07,  2.07082442e-05,
         3.09955656e-05,  6.20801988e-05,  2.73170688e-04,
         2.78781955e-03,  1.39569113e-04,  2.01203973e-04,
         1.94523894e-04,  4.18751872e-04,  8.59058132e-05,
         8.49928691e-02,  2.04124949e-03,  3.64964323e-03,
        -1.81484024e-02,  1.49451176e-03,  1.10749249e-02,
         1.64184758e-03]])

In [32]:
train_X,test_X,train_y,test_y = train_test_split(X_normal,y,random_state=7,test_size=0.3)

In [33]:
clf_3 = svm.SVC(C=1,kernel='rbf')
clf_3.fit(train_X, train_y) 

SVC(C=1)

In [34]:
y_hat_3 = clf_3.predict(test_X)
y_hat_3[0:5]

array([1, 1, 1, 1, 1])

In [35]:
print('Accuracy score: ',accuracy_score(test_y,y_hat_3))
print('F1 score:  ',f1_score(test_y,y_hat_3,average='weighted'))

Accuracy score:  0.7966101694915254
F1 score:   0.7064278861528621
